### ISSUE TITLE
Avoid code signing for iphonesimulator sdk

### ISSUE THREAD

**Issue by guidomb** [antitypical/Result#96] opened 2015-10-08 16:02 UTC
In PR #78 code signing was added for all SDK. The introduces the problem that in CI (like Travis) using Carthage 0.9.x, where code signing is not required for iphonesimulator, result build is skipped.

You can check an example build of a test project that uses Result [here](https://travis-ci.org/guidomb/ios-scripts/builds/84152934)

**Comment by gfontenot** [comment] 2015-10-08 16:26
Ha, I literally _just_ ran into this issue myself. I'm not convinced that #78 _actually_ fixed whatever it was intended to fix. I'd be interested in testing building with Carthage with that change reverted.

**Comment by JaviSoto** [comment] 2015-10-08 16:35
That PR was correct, and reverting it will break Carthage builds on people's machines. What I believe you want is to add a `sdk=iphonesimulator` rule that disables code signing, while leaving it enabled for the device.

**Comment by gfontenot** [comment] 2015-10-08 16:56
Opened #97 to handle this for the iOS simulator. I'm unclear on what the correct approach is for watchOS or tvOS (or if we should worry about those at all)

**Comment by gfontenot** [comment] 2015-10-08 19:34
#97 is merged.

**Closed by gfontenot** 2015-10-08 19:34 UTC
