### ISSUE TITLE
Release 3.0.0 can not be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by GenoZhou** [antitypical/Result#195] opened 2016-11-08 18:23 UTC
Prebuilt framwork.zip of Release 3.0.0 cannot be imported by carthage under Swift 3.0.1 environment.
Suggest we have prebuilt framwork.zip using Swift 3.0.1.

Also,
'--no-use-binaries' does work, source code can be proper compiled under Swift 3.0.1.
But if case: A(B(Result)), run '--no-use-binaries' against A will cause problem cuz carthage will still pull swift3.0 compiled prebuilt framework for building B.

**Comment by mdiep** [comment] 2016-11-08 21:01
This is a duplicate of #194.

> But if case: A(B(Result)), run '--no-use-binaries' against A will cause problem cuz carthage will still pull swift3.0 compiled prebuilt framework for building B

That should not be the case. `--no-use-binaries` should affect all dependencies. If it is, please open an issue on Carthage.

**Closed by mdiep** 2016-11-08 21:01 UTC
