### ISSUE TITLE
carthage update fails

### ISSUE THREAD

**Issue by github-user32** [antitypical/Result#88] opened 2015-09-23 05:27 UTC
My Cartfile contains only:
`github "ReactiveCocoa/ReactiveCocoa" "swift2"`

Running `cartage update` results in this error:
*Failed to discover shared schemes in project Result.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned*

*If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/antitypical/Result/issues/new*

Running `carthage update --platform iOS` avoids the problem, so I suspect there might be something in a non-iOS target of Result's Xcode project that's causing a problem.

I'm using:
Xcode 7 (7A218), and xcode-select is also configured to use those command-line tools
carthage version 0.9.1

My Cartfile.resolved contains:
`github "antitypical/Result" "0.6.0-beta.3"`
`github "ReactiveCocoa/ReactiveCocoa" "50af8fec8d1825d65c81f13efee3bbfb808a1242"`

**Comment by gfontenot** [comment] 2015-09-23 13:33
I believe this is a problem with Carthage. See similar issues Carthage/Carthage#784 and ReactiveCocoa/ReactiveCocoa#2319

**Comment by mdiep** [comment] 2015-09-23 18:10
I'm unable to reproduce this. :confused:

Can you try running `carthage update` a few more times to see if you get an error every time or just sometimes?

**Comment by gfontenot** [comment] 2015-09-23 18:18
I _have_ seen this (with RAC and Argo), but it's super intermittent. It's working for me now (El Cap GM, official Xcode 7 from the app store), but it wasn't for a few days. I'm not sure what the cause is/was.

**Comment by mdiep** [comment] 2015-09-23 18:29
If anyone sees it again, can you post the full output of `carthage update`?

**Comment by github-user32** [comment] 2015-09-23 23:59
Thanks for responding everybody. As luck would have it, I can't reproduce it now either. Yesterday it was happening reliably and since then all I've changed is to quit Xcode and restart it. If I see the problem again I'll post the full output.

**Comment by github-user32** [comment] 2015-09-24 04:24
Just managed to reproduce the problem again, although I don't think anything has changed locally that might have caused it. Here's the full output:

carthage update --verbose
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out Result at "0.6.0-beta.3"
*** Checking out ReactiveCocoa at "5b18ece9a34597c3dec6ad88d1038d936f7881ba"
Failed to discover shared schemes in project Result.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/antitypical/Result/issues/new

**Comment by gfontenot** [comment] 2015-11-26 00:22
I don't believe this is still an issue. I'm going to close it. @github-user32 if you run into this again, or if it's still an issue, feel free to re-open.

**Closed by gfontenot** 2015-11-26 00:22 UTC

**Comment by github-user32** [comment] 2015-11-26 00:30
No problem. I haven’t seen it since, but will let you know if I do. Thanks.
