### ISSUE TITLE
Carthage build failure

### ISSUE THREAD

**Issue by adly-holler** [antitypical/Result#25] opened 2015-04-16 00:40 UTC
Create a cartfile like

`github "antitypical/Result" ~> 0.1`

Using carthage 0.6.4, run

`carthage bootstrap --platform iOS`

You'll get 
```
*** Building scheme "Box-iOS" in Box.xcodeproj
*** Building scheme "Prelude-iOS" in Prelude.xcodeproj
*** Building scheme "Either-iOS" in Either.xcworkspace
*** Building scheme "Result-iOS" in Result.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

There are a couple issues in the log file. It seems to be building the Mac versions of the frameworks as well as the iOS versions, despite telling Carthage the platform. As for the build failing, the last message of the log is 

```
=== BUILD TARGET Prelude-Mac OF PROJECT Prelude WITH CONFIGURATION Release ===

Check dependencies
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'
```

**Comment by robrix** [comment] 2015-04-16 02:52
Duplicate of #21. I think our best bet is going to be binary releases.

**Comment by robrix** [comment] 2015-04-16 02:55
@jspahrsummers Is there any reason building with Xcode proper wouldn’t work for binary releases?

**Comment by jspahrsummers** [comment] 2015-04-16 04:00
@robrix That should work, although I'd be cautious about relying upon it. There are a variety of scenarios where binaries may not be downloaded (user choice, API issues, rate limiting, etc.). Carthage basically just considers them an optimization, and tries not to expect them to be present.

**Comment by robrix** [comment] 2015-04-16 13:19
The alternative here is for Apple to fix my radar. They closed it as a dupe. I can’t imagine it’ll happen this year, and probably not ever.

**Comment by robrix** [comment] 2015-04-16 13:21
I think I’m content with a binary release as a way to mitigate the effects of this `xcodebuild` bug. Gonna close this and upload a binary.

**Closed by robrix** 2015-04-16 13:21 UTC
Labels: duplicate

**Comment by robrix** [comment] 2015-04-16 13:38
Argh. It occurs to me I don’t know how to handle the iOS binaries. Do I lipo the sim & device images together…?

**Comment by jspahrsummers** [comment] 2015-04-17 22:30
@robrix If you can get `carthage build --no-skip-current --platform iOS` to work, that would be ideal—even if it's by deleting or disabling the Mac scheme temporarily somehow.

**Comment by robrix** [comment] 2015-04-17 22:37
:+1:
